CREATE TABLE IF NOT EXISTS director(
    director_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL UNIQUE,
    birthday DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS friendship_status (
    status_id BIGINT PRIMARY KEY,
    name VARCHAR(25) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    PRIMARY KEY(user_id,friend_id),
    FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY(friend_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY(status_id) REFERENCES friendship_status(status_id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS mpa_rating (
    rating_id BIGINT PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_id BIGINT,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE,
    duration INT NOT NULL,
    director_id BIGINT,
    FOREIGN KEY(rating_id) REFERENCES mpa_rating(rating_id) ON DELETE RESTRICT,
    FOREIGN KEY(director_id) REFERENCES director(director_id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS favorite_films (
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    PRIMARY KEY(user_id,film_id),
    FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY(film_id) REFERENCES films(film_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS genres (
    genre_id BIGINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL,
    genre_id BIGINT,
    PRIMARY KEY(film_id,genre_id),
    FOREIGN KEY(film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY(genre_id) REFERENCES genres(genre_id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS directors (
    director_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors (
    film_id BIGINT NOT NULL,
    director_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, director_id),
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES directors (director_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(2000) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    useful INTEGER DEFAULT 0,
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_film FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
    CONSTRAINT uk_user_film UNIQUE (user_id, film_id)
);
CREATE TABLE IF NOT EXISTS review_likes (
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (review_id, user_id),
    CONSTRAINT fk_review_like_review FOREIGN KEY (review_id) REFERENCES reviews (review_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_like_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS review_dislikes (
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (review_id, user_id),
    CONSTRAINT fk_review_dislike_review FOREIGN KEY (review_id) REFERENCES reviews (review_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_dislike_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS event_type (
                                          event_type_id BIGINT PRIMARY KEY,
                                          name VARCHAR(20) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS operation_type (
                                              operation_id BIGINT PRIMARY KEY,
                                              name VARCHAR(10) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS events (
                                      event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      timestamp BIGINT NOT NULL,
                                      user_id BIGINT NOT NULL,
                                      event_type VARCHAR(20) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    entity_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
    );

//Инициализация БД с новостями\ивентами
